# Generated by Django 4.2.7 on 2023-11-14 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REN', 'RENTED'), ('RET', 'RETURNED')], default='REN')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('days_rented', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRentalApp.client')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRentalApp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('production_year', models.IntegerField(null=True)),
                ('pegi', models.IntegerField(default=18)),
                ('movie_length', models.IntegerField()),
                ('dubbing', models.ManyToManyField(blank=True, related_name='moviedetails_dubbing', to='movieRentalApp.language')),
                ('languages', models.ManyToManyField(related_name='moviedetails_languages', to='movieRentalApp.language')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieRentalApp.movie')),
                ('subtitles', models.ManyToManyField(blank=True, related_name='moviedetails_subtitles', to='movieRentalApp.language')),
            ],
        ),
    ]
