# Generated by Django 4.2.7 on 2023-11-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('zip_code', models.CharField()),
                ('street', models.CharField(blank=True, null=True)),
                ('building_number', models.CharField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieRentalApp.client')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='category',
            field=models.ManyToManyField(to='movieRentalApp.category'),
        ),
    ]
